apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: 'grafana'
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: '16.1'
      timescaledb: false
