{
 "title": "Ecommerce monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Revenue and Profit (last hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT total_amount as revenue, profit, checkout_timestamp FROM checkout_attribution WHERE checkout_timestamp >= now() - INTERVAL '1 hour';"
    }
   ]
  },
  {
   "title": "Customer Checkout Source (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT source, COUNT(source) AS count\nFROM checkout_attribution\nWHERE checkout_timestamp >= now() -  INTERVAL '1 hour'\nGROUP BY source\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Most Popular Product Category (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT category, COUNT(category) AS count\nFROM checkout_attribution\nWHERE checkout_timestamp >= now() -  INTERVAL '1 hour'\nGROUP BY category\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Customer's Gender (last hour)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(gender) as count\nFROM checkout_attribution\nWHERE checkout_timestamp >= now() - INTERVAL '1 hour'\nGROUP BY (gender)\n\n"
    }
   ]
  },
  {
   "title": "Fail Payment (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT payment_description, COUNT(payment_description) AS count\nFROM checkout_attribution\nWHERE checkout_timestamp >= now() -  INTERVAL '1 hour'\nAND payment_description != 'None'\nGROUP BY payment_description\nORDER BY count DESC"
    }
   ]
  }
 ]
}